lib/parzival_web/router.ex
defmodule ParzivalWeb.Router do
  use ParzivalWeb, :router

  import ParzivalWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ParzivalWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ParzivalWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/register/:qr", UserRegistrationController, :new
    post "/register/:qr", UserRegistrationController, :create
    get "/login", UserSessionController, :new
    post "/login", UserSessionController, :create
    get "/reset_password", UserResetPasswordController, :new
    post "/reset_password", UserResetPasswordController, :create
    get "/reset_password/:token", UserResetPasswordController, :edit
    put "/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ParzivalWeb do
    pipe_through [:browser]

    live_session :user, on_mount: [{ParzivalWeb.Hooks, :current_user}] do
      scope "/", Landing, as: :landing do
        live "/", HomeLive.Index, :index

        live "/schedule", ScheduleLive.Index, :index
        live "/missions", MissionsLive.Index, :index
        # live "/speakers", SpeakersLive.Index, :index
        live "/faqs", FaqsLive.Index, :index
        # live "/team", TeamLive.Index, :index
      end

      scope "/", App do
        live "/profile/:qr", ProfileLive.Show, :qr_show
      end
    end
  end

  scope "/", ParzivalWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :logged_in, on_mount: [{ParzivalWeb.Hooks, :current_user}] do
      scope "/app", App do
        live "/", DashboardLive.Index, :index
        live "/profile/:id", ProfileLive.Show, :show

        pipe_through [:require_admin]
        live "/companies/new", CompanyLive.New, :new
        live "/companies/:id/edit", CompanyLive.Edit, :edit

        pipe_through [:require_admin_or_recruiter]
        live "/offers/new", OfferLive.New, :new
        live "/offers/:id/edit", OfferLive.Edit, :edit

        live "/offers/", OfferLive.Index, :index
        live "/offers/:id", OfferLive.Show, :show

        live "/companies/", CompanyLive.Index, :index
        live "/companies/:id", CompanyLive.Show, :show

        live "/leaderboard", LeaderboardLive.Index, :index

        live "/store/", ProductLive.Index, :index
        live "/store/:id", ProductLive.Show, :show

        live "/boosts/", BoostLive.Index, :index
        live "/boosts/:id", BoostLive.Show, :show

        live "/vault", OrderLive.Index, :index

        live "/announcements", AnnouncementLive.Index, :index
        live "/announcements/:id", AnnouncementLive.Show, :show

        live "/missions", MissionLive.Index, :index

        live "/connections", ConnectionLive.Index, :index

        scope "/missions" do
          pipe_through [:require_level]
          live "/:id", MissionLive.Show, :show

          live "/:id/tasks/:task_id", TaskLive.Show, :show
          live "/:id/tasks/:task_id/redeem", TaskLive.Show, :redeem
        end

        pipe_through [:require_order_attendee]
        live "/vault/:id", OrderLive.Show, :show

        pipe_through [:require_curriculum_attendee]
        live "/profile/:id/edit", ProfileLive.Edit, :edit
        live "/dashboard/curriculum", DashboardLive.Edit, :edit
      end

      scope "/admin", Backoffice, as: :admin do
        scope "/tools" do
          live "/faqs/", FaqsLive.Index, :index
          live "/faqs/:id", FaqsLive.Show, :show
        end

        pipe_through [:require_not_attendee]
        live "/scanner", ScannerLive.Index, :index
        live "/task_redeem/:task_id/:attendee_id", TaskLive.Redeem, :redeem

        pipe_through [:require_admin]
        live "/missions/new", MissionLive.New, :new
        live "/missions/:id/edit", MissionLive.Edit, :edit
        live "/accounts/", UserLive.Index, :index
        live "/accounts/new", UserLive.New, :new

        scope "/jobs" do
          live "/types/", OfferTypeLive.Index, :index
          live "/types/new", OfferTypeLive.Index, :new
          live "/types/:id/edit", OfferTypeLive.Index, :edit

          live "/times/", OfferTimeLive.Index, :index
          live "/times/new", OfferTimeLive.Index, :new
          live "/times/:id/edit", OfferTimeLive.Index, :edit
        end

        scope "/companies" do
          live "/levels/", LevelLive.Index, :index
          live "/levels/new", LevelLive.Index, :new
          live "/levels/:id/edit", LevelLive.Index, :edit
        end

        live "/store/new", ProductLive.New, :new
        live "/store/:id/edit", ProductLive.Edit, :edit
        live "/order/:id/redeem", OrderLive.Edit, :edit

        live "/boosts/new", BoostLive.New, :new
        live "/boosts/:id/edit", BoostLive.Edit, :edit

        scope "/missions" do
          live "/new", MissionLive.New, :new
          live "/:id/edit", MissionLive.Edit, :edit

          live "/difficulty/", DifficultyLive.Index, :index
          live "/difficulty/new", DifficultyLive.Index, :new
          live "/difficulty/:id/edit", DifficultyLive.Index, :edit
        end

        scope "/tools" do
          live "/new", FaqsLive.New, :new
          live "/faqs/:id/edit", FaqsLive.Edit, :edit
          live "/announcements/new", AnnouncementLive.New, :new
          live "/announcements/:id/edit", AnnouncementLive.Edit, :edit
        end
      end

      get "/settings", UserSettingsController, :edit
      put "/settings", UserSettingsController, :update
      get "/settings/confirm_email/:token", UserSettingsController, :confirm_email
      get "/cv/:attendee_id", PdfController, :download_cv
      get "/cv/preview", PdfController, :preview_cv

      pipe_through [:require_admin]
      get "/export_atteendes", CsvController, :create
    end
  end

  scope "/", ParzivalWeb do
    pipe_through [:browser]

    delete "/log_out", UserSessionController, :delete
    get "/confirm", UserConfirmationController, :new
    post "/confirm", UserConfirmationController, :create
    get "/confirm/:token", UserConfirmationController, :edit
    post "/confirm/:token", UserConfirmationController, :update
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: ParzivalWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/parzival_web/live/app/company_live/edit.ex
defmodule ParzivalWeb.App.CompanyLive.Edit do
  @moduledoc false
  use ParzivalWeb, :live_view

  alias Parzival.Companies

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:current_page, :companies)
     |> assign(:page_title, "Edit Company")
     |> assign(:company, Companies.get_company!(id))}
  end
end

lib/parzival_web/live/app/company_live/form_component.ex
defmodule ParzivalWeb.App.CompanyLive.FormComponent do
  @moduledoc false
  use ParzivalWeb, :live_component

  alias Parzival.Companies

  @extensions_whitelist ~w(.jpg .jpeg .gif .png)

  @impl true
  def mount(socket) do
    {:ok,
     socket
     |> allow_upload(:picture, accept: @extensions_whitelist, max_entries: 1)}
  end

  @impl true
  def update(%{company: company} = assigns, socket) do
    changeset = Companies.change_company(company)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)
     |> assign(list_levels(assigns))}
  end

  @impl true
  def handle_event("validate", %{"company" => company_params}, socket) do
    changeset =
      socket.assigns.company
      |> Companies.change_company(company_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"company" => company_params}, socket) do
    save_company(socket, socket.assigns.action, company_params)
  end

  defp save_company(socket, :edit, company_params) do
    case Companies.update_company(
           socket.assigns.company,
           company_params,
           &consume_picture_data(socket, &1)
         ) do
      {:ok, _company} ->
        {:noreply,
         socket
         |> put_flash(:success, "Company updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_company(socket, :new, company_params) do
    case Companies.create_company(company_params, &consume_picture_data(socket, &1)) do
      {:ok, _company} ->
        {:noreply,
         socket
         |> put_flash(:success, "Company created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end

  defp consume_picture_data(socket, company) do
    consume_uploaded_entries(socket, :picture, fn %{path: path}, entry ->
      Companies.update_company_picture(company, %{
        "picture" => %Plug.Upload{
          content_type: entry.client_type,
          filename: entry.client_name,
          path: path
        }
      })
    end)
    |> case do
      [{:ok, company}] ->
        {:ok, company}

      _errors ->
        {:ok, company}
    end
  end

  defp list_levels(params) do
    case Companies.list_levels(params) do
      {:ok, {levels, _meta}} ->
        %{levels: levels}

      {:error, _flop} ->
        %{levels: []}
    end
  end
end

lib/parzival_web/live/app/company_live/index.ex
defmodule ParzivalWeb.App.CompanyLive.Index do
  @moduledoc false
  use ParzivalWeb, :live_view

  import ParzivalWeb.Components.Pagination

  alias Parzival.Companies
  alias Parzival.Uploaders

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply,
     socket
     |> assign(:current_page, :companies)
     |> assign(:params, params)
     |> assign(list_companies(params))}
  end

  defp list_companies(params) do
    case Companies.list_companies(params, preloads: :level) do
      {:ok, {companies, meta}} ->
        %{companies: companies, meta: meta}

      {:error, flop} ->
        %{companies: [], meta: flop}
    end
  end

  @impl true
  def handle_event("search", %{"search" => %{"query" => query}}, socket) do
    params = build_search_map(socket.assigns.params, query)

    {:noreply, push_patch(socket, to: Routes.company_index_path(socket, :index, params))}
  end

  defp build_search_map(params, text) do
    filters =
      (params["filters"] || %{})
      |> Map.put("1", %{"field" => "search", "value" => text, "op" => "ilike_or"})

    Map.put(params, "filters", filters)
  end
end

lib/parzival_web/live/app/company_live/new.ex
defmodule ParzivalWeb.App.CompanyLive.New do
  @moduledoc false
  use ParzivalWeb, :live_view

  alias Parzival.Companies.Company

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(_params, _, socket) do
    {:noreply,
     socket
     |> assign(:current_page, :companies)
     |> assign(:page_title, "New Company")
     |> assign(:company, %Company{})}
  end
end

lib/parzival_web/live/app/company_live/show.ex
defmodule ParzivalWeb.App.CompanyLive.Show do
  @moduledoc false
  use ParzivalWeb, :live_view

  import ParzivalWeb.Components.Pagination

  alias Parzival.Accounts
  alias Parzival.Companies
  alias Parzival.Uploaders

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id} = params, _, socket) do
    {:noreply,
     socket
     |> assign(:current_page, :companies)
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:company, Companies.get_company!(id, preloads: :level))
     |> assign(:params, params)
     |> assign(:recruiters, list_recruiters(params))
     |> assign(list_offers(params))}
  end

  @impl true
  def handle_event("delete", _payload, socket) do
    case Companies.delete_company(socket.assigns.company) do
      {:ok, _company} ->
        {:noreply,
         socket
         |> put_flash(:success, "Company deleted successfully!")
         |> push_redirect(to: Routes.company_index_path(socket, :index))}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply,
         socket
         |> put_flash(:error, elem(changeset.errors[:error], 0))
         |> assign(:changeset, changeset)}
    end
  end

  defp list_offers(%{"id" => id} = params) do
    params =
      params
      |> Map.put("page_size", 6)

    case Companies.list_offers(
           params,
           preloads: [:company, :offer_type, :offer_time],
           where: [company_id: id]
         ) do
      {:ok, {offers, meta}} ->
        %{offers: offers, offers_meta: meta}

      {:error, flop} ->
        %{offers: [], offers_meta: flop}
    end
  end

  defp list_recruiters(%{"id" => id}) do
    Accounts.list_users(
      preloads: :company,
      where: [company_id: id]
    )
  end

  defp page_title(:show), do: "Show Company"
end

lib/parzival_web/live/backoffice/company/company_live/edit.ex
defmodule ParzivalWeb.Backoffice.CompanyLive.Edit do
  @moduledoc false
  use ParzivalWeb, :live_view

  alias Parzival.Companies

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:current_page, :companies)
     |> assign(:page_title, "Edit Company")
     |> assign(:company, Companies.get_company!(id))}
  end
end

lib/parzival_web/live/backoffice/company/company_live/form_component.ex
defmodule ParzivalWeb.Backoffice.CompanyLive.FormComponent do
  @moduledoc false
  use ParzivalWeb, :live_component

  alias Parzival.Companies

  @impl true
  def update(%{company: company} = assigns, socket) do
    changeset = Companies.change_company(company)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)
     |> assign(list_levels(assigns))}
  end

  @impl true
  def handle_event("validate", %{"company" => company_params}, socket) do
    changeset =
      socket.assigns.company
      |> Companies.change_company(company_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"company" => company_params}, socket) do
    save_company(socket, socket.assigns.action, company_params)
  end

  defp save_company(socket, :edit, company_params) do
    case Companies.update_company(socket.assigns.company, company_params) do
      {:ok, _company} ->
        {:noreply,
         socket
         |> put_flash(:success, "Company updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_company(socket, :new, company_params) do
    case Companies.create_company(company_params) do
      {:ok, _company} ->
        {:noreply,
         socket
         |> put_flash(:success, "Company created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end

  defp list_levels(params) do
    case Companies.list_levels(params) do
      {:ok, {levels, _meta}} ->
        %{levels: levels}

      {:error, _flop} ->
        %{levels: []}
    end
  end
end

lib/parzival_web/live/backoffice/company/company_live/new.ex
defmodule ParzivalWeb.Backoffice.CompanyLive.New do
  @moduledoc false
  use ParzivalWeb, :live_view

  alias Parzival.Companies.Company

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(_params, _, socket) do
    {:noreply,
     socket
     |> assign(:current_page, :companies)
     |> assign(:page_title, "New Company")
     |> assign(:company, %Company{})}
  end
end

lib/parzival_web/live/app/company_live/edit.html.heex
<.live_component module={ParzivalWeb.App.CompanyLive.FormComponent} id={@company.id} title={@page_title} action={@live_action} company={@company} current_user={@current_user} return_to={Routes.company_show_path(@socket, :show, @company)} />

lib/parzival_web/live/app/company_live/form_component.html.heex
<div class="min-h-full border-r border-gray-200">
  <.form let={f} for={@changeset} id="company-form" phx-target={@myself} phx-change="validate" phx-submit="save">
    <div class="py-5 pr-6 pl-4 border-gray-200 sm:px-6 lg:px-8 xl:py-6 xl:px-6 border-y">
      <div class="flex justify-between items-center h-10">
        <h1 class="flex-1 text-lg font-medium">Company</h1>
        <%= if @current_user.role in [:admin] || @current_user.role in [:recruiter] && @current_user.company_id == @company.id do %>
          <div class="flex mt-5 space-x-2 xl:mt-0 xl:ml-4">
            <%= submit do %>
              <div type="button" class="inline-flex justify-center items-center py-2 px-4 text-sm font-medium text-white rounded-md border border-transparent shadow-sm xl:w-full bg-secondary hover:bg-primary">
                Save
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="relative py-5 px-4 border-b border-gray-200 sm:py-6 sm:px-6 md:border-b-0 lg:px-8 xl:px-6">
      <div>
        <%= live_redirect("< Back", to: @return_to, class: "hover:underline inline-flex items-center justify-center whitespace-nowrap") %>
      </div>
      <div class="px-4 sm:px-0">
        <div class="flex flex-col justify-center items-center mt-6 sm:flex-row sm:gap-x-5">
          <%= live_file_input(@uploads.picture, class: "hidden") %>
          <a onclick={"document.getElementById('#{@uploads.picture.ref}').click()"}>
            <div class={"#{if length(@uploads.picture.entries) != 0 do
                "hidden"
              end} relative w-24 h-24 ring-4 ring-white rounded-full cursor-pointer bg-secondary sm:w-32 group sm:h-32 hover:bg-tertiary"}>
              <div class="flex absolute justify-center items-center w-full h-full">
                <Heroicons.Outline.camera class="mx-auto w-12 h-12 text-white group-hover:text-opacity-70" />
              </div>
            </div>
            <section>
              <%= for entry <- @uploads.picture.entries do %>
                <%= for err <- upload_errors(@uploads.picture, entry) do %>
                  <p class="alert alert-danger"><%= Phoenix.Naming.humanize(err) %></p>
                <% end %>
                <article class="flex relative items-center w-24 h-24 bg-white rounded-full cursor-pointer sm:w-32 sm:h-32 upload-entry group">
                  <div class="flex absolute z-10 justify-center items-center w-full h-full rounded-full">
                    <Heroicons.Outline.camera class="mx-auto w-12 h-12 text-white text-opacity-0 rounded-full group-hover:text-opacity-100" />
                  </div>
                  <figure class="flex justify-center items-center w-full h-full rounded-full group-hover:opacity-80">
                    <%= live_img_preview(entry, class: "object-cover object-center rounded-full w-24 h-24 sm:w-32 sm:h-32 border-4 border-white") %>
                  </figure>
                </article>
              <% end %>
            </section>
          </a>
          <div class="flex flex-col gap-y-1 w-full">
            <%= text_input(f, :name, placeholder: "Choose title", phx_debounce: "blur", class: "mt-6 text-gray-800 text-2xl leading-7 text-gray-900 sm:text-3xl sm:truncate mt-1 font-bold focus:ring-red-500 focus:border-red-500 block w-full shadow-sm border-gray-300 rounded-md") %>
            <div class="flex text-red-500">
              <%= error_tag(f, :name) %>
            </div>
            <%= if @current_user.role in [:admin] do %>
              <%= select(f, :level_id, Enum.map(@levels, &{&1.name, &1.id}), prompt: "Choose a Sponsorship Level", selected: f.data.level_id, class: "mt-1 block border-gray-300 rounded-md w-full shadow-sm sm:w-64 focus:ring-red-800 focus:border-red-800") %>
              <div class="flex text-red-500">
                <%= error_tag(f, :level_id) %>
              </div>
            <% end %>
            <%= textarea(f, :description, placeholder: "Choose description", rows: 3, phx_debounce: "blur", class: "mt-1 text-gray-500 focus:ring-red-500 focus:border-red-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md") %>
            <div class="flex text-red-500">
              <%= error_tag(f, :description) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </.form>
</div>

lib/parzival_web/live/app/company_live/index.html.heex
<div class="min-h-full bg-white border-r border-gray-200">
  <div class="pt-5 pr-6 pb-5 pl-4 border-gray-200 sm:pl-6 lg:pl-8 xl:pt-6 xl:pl-6 border-y">
    <div class="flex justify-between items-center h-10">
      <h1 class="flex-1 text-lg font-medium">Companies</h1>
      <%= if @current_user.role in [:admin, :recruiter] do %>
        <div class="flex flex-col sm:flex-row xl:flex-col">
          <%= live_patch("New", to: Routes.company_new_path(@socket, :new), class: "inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-secondary hover:bg-primary xl:w-full") %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="flex flex-1 justify-center items-center">
    <div class="w-full border-b border-gray-200">
      <label for="search" class="sr-only">Search</label>
      <form phx-submit="search" phx-change="search" class="relative" method="#">
        <div class="flex absolute inset-y-0 left-0 items-center pl-6 pointer-events-none">
          <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 20 20">
            <path fill="currentColor" fill-rule="evenodd" d="M8 4a4 4 0 1 0 0 8a4 4 0 0 0 0-8ZM2 8a6 6 0 1 1 10.89 3.476l4.817 4.817a1 1 0 0 1-1.414 1.414l-4.816-4.816A6 6 0 0 1 2 8Z" clip-rule="evenodd" />
          </svg>
        </div>
        <%= text_input(:search, :query,
          placeholder: "Search",
          autofocus: true,
          "phx-debounce": "300",
          class: "block w-full py-3 pl-14 pr-3 leading-5 placeholder-gray-400 bg-white border-0 focus:ring-primary focus:ring-0 focus:outline-none"
        ) %>
      </form>
    </div>
  </div>
  <ul role="list" class="relative z-0">
    <%= for company <- @companies do %>
      <%= live_redirect to: Routes.company_show_path(@socket, :show, company) do %>
        <li id={"company-#{company.id}"} class="relative pr-6 border-b border-gray-200 hover:bg-gray-50">
          <div class="flex justify-between items-center">
            <div class="py-4 pr-3 pl-4 text-sm whitespace-nowrap sm:pl-6">
              <div class="flex items-center">
                <div>
                  <%= if is_nil(Uploaders.ProfilePicture.url({company.picture, company}, :medium)) do %>
                    <div class="relative flex-shrink-0 rounded-2xl ring-4 ring-white min-w-24 min-h-24 sm:min-w-32 sm:min-h-32">
                      <span class="inline-flex justify-center items-center w-24 h-24 rounded-2xl sm:w-32 sm:h-32 bg-secondary">
                        <span class="text-4xl font-medium leading-none text-white select-none sm:text-5xl">
                          <%= extract_initials(company.name) %>
                        </span>
                      </span>
                    </div>
                  <% else %>
                    <div class="relative flex-shrink-0 w-24 h-24 bg-white rounded-2xl ring-4 ring-white sm:w-32 sm:h-32">
                      <img src={Uploaders.ProfilePicture.url({company.picture, company}, :medium)} class="object-center absolute rounded-2xl w-[98px] h-[98px] sm:w-[130px] sm:h-[130px]" />
                    </div>
                  <% end %>
                </div>
                <div class="ml-4">
                  <div class="font-medium text-gray-900">
                    <%= company.name %>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <span class={"inline-flex items-center justify-center px-2 text-xs font-semibold leading-5 border #{border_200(company.level.color)} #{bg_100(company.level.color)} rounded-2xl"}>
                <%= company.level.name %>
              </span>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
  <.pagination items={@companies} meta={@meta} params={@params} class="flex justify-between items-center w-full" />
</div>

lib/parzival_web/live/app/company_live/new.html.heex
<.live_component module={ParzivalWeb.App.CompanyLive.FormComponent} id={:new} title={@page_title} action={@live_action} company={@company} current_user={@current_user} return_to={Routes.company_index_path(@socket, :index)} />